[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]

[[notifications]]
  form = "contact"
  to = "lenka.baricova@post.cz"
  subject = "New contact form submission"
  body = """
  You have received a new submission from your contact form.

  Name: {{name}}
  Email: {{email}}
  Message: {{message}}
  """